apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: test-partition
  namespace: default
spec:
  replicas: 4
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      partition: 2
  gameServerTemplate:
    spec:
      containers:
        - image: nginx:1.23
          name: minecraft
